variables:
  msbuild: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe'

build_windows:
  stage: build
  script:
    - echo "Release build..."
    - '"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe" -p:Configuration=Debug -p:Platform="x64" -m ".\WarHammerV2.sln"'
  tags:
    - shared-windows
    - windows
    - windows-1809