variables:
  msbuild: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe'

build_windows:
  stage: build
  script:
    - '& "$msbuild WarHammerV2.sln"  -help'
  tags:
    - shared-windows
    - windows
    - windows-1809